import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

/**
 * GET /api/challenges
 * Returns list of challenges with optional filters
 * Query params:
 * - status: "active" | "upcoming" | "past"
 * - type: "speed" | "streak" | "completion"
 */
export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const status = searchParams.get("status");
    const type = searchParams.get("type");

    const now = new Date();
    let dateFilter = {};

    // Filter by status
    if (status === "active") {
      dateFilter = {
        startDate: { lte: now },
        endDate: { gte: now },
      };
    } else if (status === "upcoming") {
      dateFilter = {
        startDate: { gt: now },
      };
    } else if (status === "past") {
      dateFilter = {
        endDate: { lt: now },
      };
    }

    const challenges = await prisma.challenge.findMany({
      where: {
        isActive: true,
        ...(type && { type }),
        ...dateFilter,
      },
      include: {
        creator: {
          select: {
            id: true,
            name: true,
          },
        },
        _count: {
          select: {
            participants: true,
          },
        },
      },
      orderBy: {
        startDate: "desc",
      },
    });

    return NextResponse.json({
      data: challenges,
      count: challenges.length,
    });
  } catch (error) {
    console.error("Error fetching challenges:", error);
    return NextResponse.json(
      { error: "Failed to fetch challenges" },
      { status: 500 }
    );
  }
}

/**
 * POST /api/challenges
 * Create a new user-created challenge (requires eligibility)
 */
export async function POST(request: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    // Import validation and permission helpers
    const { challengeCreateSchema } = await import("@/lib/validations");
    const {
      checkChallengeCreationEligibility,
      countActiveUserChallenges,
    } = await import("@/lib/challenges");

    // Check eligibility
    const eligibility = await checkChallengeCreationEligibility(session.user.id);
    if (!eligibility.eligible) {
      return NextResponse.json(
        {
          error: "You are not eligible to create challenges",
          details: {
            tenure: eligibility.tenure,
            currentStreak: eligibility.currentStreak,
            tenureRequired: eligibility.tenureRequired,
            streakRequired: eligibility.streakRequired,
          },
        },
        { status: 403 }
      );
    }

    // Check active challenge limit (max 1)
    const activeCount = await countActiveUserChallenges(session.user.id);
    if (activeCount >= 1) {
      return NextResponse.json(
        { error: "You already have an active challenge. You can only create 1 at a time." },
        { status: 403 }
      );
    }

    // Validate request body
    const body = await request.json();
    const validatedData = challengeCreateSchema.parse(body);

    // Create challenge
    const challenge = await prisma.challenge.create({
      data: {
        type: validatedData.type,
        title: validatedData.title,
        description: validatedData.description,
        startDate: new Date(validatedData.startDate),
        endDate: new Date(validatedData.endDate),
        targetValue: validatedData.targetValue,
        isActive: true,
        isAutoGenerated: false,
        createdBy: session.user.id,
      },
    });

    return NextResponse.json({ data: challenge });
  } catch (error) {
    console.error("Error creating challenge:", error);

    // Handle validation errors
    if (error instanceof Error && error.name === "ZodError") {
      return NextResponse.json(
        { error: "Validation failed", details: error },
        { status: 400 }
      );
    }

    return NextResponse.json(
      { error: "Failed to create challenge" },
      { status: 500 }
    );
  }
}
