import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

/**
 * GET /api/challenges
 * Returns list of challenges with optional filters
 * Query params:
 * - status: "active" | "upcoming" | "past"
 * - type: "speed" | "streak" | "completion"
 */
export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const status = searchParams.get("status");
    const type = searchParams.get("type");

    const now = new Date();
    let dateFilter = {};

    // Filter by status
    if (status === "active") {
      dateFilter = {
        startDate: { lte: now },
        endDate: { gte: now },
      };
    } else if (status === "upcoming") {
      dateFilter = {
        startDate: { gt: now },
      };
    } else if (status === "past") {
      dateFilter = {
        endDate: { lt: now },
      };
    }

    const challenges = await prisma.challenge.findMany({
      where: {
        isActive: true,
        ...(type && { type }),
        ...dateFilter,
      },
      include: {
        _count: {
          select: {
            participants: true,
          },
        },
      },
      orderBy: {
        startDate: "desc",
      },
    });

    return NextResponse.json({
      data: challenges,
      count: challenges.length,
    });
  } catch (error) {
    console.error("Error fetching challenges:", error);
    return NextResponse.json(
      { error: "Failed to fetch challenges" },
      { status: 500 }
    );
  }
}

/**
 * POST /api/challenges
 * Create a new challenge (admin only for now)
 */
export async function POST(request: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const body = await request.json();
    const { type, title, description, startDate, endDate, targetValue } = body;

    // Validate required fields
    if (!type || !title || !startDate || !endDate || !targetValue) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    // Validate dates
    const start = new Date(startDate);
    const end = new Date(endDate);
    if (start >= end) {
      return NextResponse.json(
        { error: "Start date must be before end date" },
        { status: 400 }
      );
    }

    const challenge = await prisma.challenge.create({
      data: {
        type,
        title,
        description,
        startDate: start,
        endDate: end,
        targetValue: parseInt(targetValue),
        isActive: true,
        isAutoGenerated: false,
      },
    });

    return NextResponse.json({ data: challenge });
  } catch (error) {
    console.error("Error creating challenge:", error);
    return NextResponse.json(
      { error: "Failed to create challenge" },
      { status: 500 }
    );
  }
}
