/**
 * Challenge system logic
 */

import { prisma } from "./prisma";
import { Challenge, ChallengeParticipant, DailyLog } from "@prisma/client";
import { startOfWeek, endOfWeek, addDays, differenceInDays } from "date-fns";
import { calculateStreak } from "./stats";

/**
 * Calculate user's progress for a challenge based on type
 */
export async function calculateUserProgressForChallenge(
  userId: string,
  challenge: Challenge
): Promise<number> {
  const startDate = new Date(challenge.startDate);
  const endDate = new Date(challenge.endDate);

  // Get all user's logs within challenge period
  const logs = await prisma.dailyLog.findMany({
    where: {
      project: {
        userId,
      },
      date: {
        gte: startDate,
        lte: endDate,
      },
    },
    orderBy: {
      date: "asc",
    },
  });

  // Calculate progress based on challenge type
  switch (challenge.type) {
    case "speed":
      // Sum of all daily stitches in period
      return logs.reduce((sum, log) => sum + log.dailyStitches, 0);

    case "streak":
      // Use existing streak calculation
      const { currentStreak } = calculateStreak(logs);
      return currentStreak;

    case "completion":
      // Number of completed projects during period
      const completedProjects = await prisma.project.count({
        where: {
          userId,
          status: "completed",
          updatedAt: {
            gte: startDate,
            lte: endDate,
          },
        },
      });
      return completedProjects;

    default:
      return 0;
  }
}

/**
 * Update or create leaderboard entry for a user in a challenge
 */
export async function updateLeaderboardEntry(
  challengeId: string,
  userId: string,
  score: number
): Promise<void> {
  await prisma.challengeLeaderboard.upsert({
    where: {
      challengeId_userId: {
        challengeId,
        userId,
      },
    },
    update: {
      score,
      updatedAt: new Date(),
    },
    create: {
      challengeId,
      userId,
      score,
      rank: 0, // Will be recalculated
    },
  });

  // Update participant progress as well
  await prisma.challengeParticipant.update({
    where: {
      challengeId_userId: {
        challengeId,
        userId,
      },
    },
    data: {
      currentProgress: score,
      lastUpdated: new Date(),
    },
  });
}

/**
 * Recalculate ranks for all participants in a challenge
 * Should be called periodically (cron job) or after significant updates
 */
export async function recalculateRanks(challengeId: string): Promise<void> {
  // Get all leaderboard entries sorted by score
  const entries = await prisma.challengeLeaderboard.findMany({
    where: { challengeId },
    orderBy: { score: "desc" },
  });

  // Assign ranks (handling ties)
  let currentRank = 1;
  let previousScore: number | null = null;
  let sameRankCount = 0;

  for (const entry of entries) {
    if (previousScore !== null && entry.score < previousScore) {
      currentRank += sameRankCount;
      sameRankCount = 1;
    } else {
      sameRankCount++;
    }

    await prisma.challengeLeaderboard.update({
      where: { id: entry.id },
      data: { rank: currentRank },
    });

    previousScore = entry.score;
  }
}

/**
 * Generate a weekly speed challenge
 * To be called by cron job every Monday
 */
export async function generateWeeklySpeedChallenge(): Promise<Challenge> {
  const now = new Date();
  const startDate = startOfWeek(now, { weekStartsOn: 1 }); // Monday
  const endDate = endOfWeek(now, { weekStartsOn: 1 }); // Sunday

  // Calculate week number
  const weekNumber = Math.ceil(
    (differenceInDays(startDate, new Date(startDate.getFullYear(), 0, 1)) + 1) / 7
  );

  const challenge = await prisma.challenge.create({
    data: {
      type: "speed",
      title: `Weekly Speed Challenge - Week ${weekNumber}`,
      description: `Stitch as many stitches as you can this week! Top 10 fastest stitchers will be featured on the leaderboard.`,
      startDate,
      endDate,
      targetValue: 10000, // Target: 10k stitches per week
      isActive: true,
      isAutoGenerated: true,
    },
  });

  return challenge;
}

/**
 * Get active challenges (within date range)
 */
export async function getActiveChallenges(): Promise<Challenge[]> {
  const now = new Date();

  return await prisma.challenge.findMany({
    where: {
      isActive: true,
      startDate: {
        lte: now,
      },
      endDate: {
        gte: now,
      },
    },
    orderBy: {
      startDate: "desc",
    },
  });
}

/**
 * Get user's participation in a challenge
 */
export async function getUserChallengeParticipation(
  userId: string,
  challengeId: string
): Promise<ChallengeParticipant | null> {
  return await prisma.challengeParticipant.findUnique({
    where: {
      challengeId_userId: {
        challengeId,
        userId,
      },
    },
  });
}

/**
 * Join a challenge (create participation record)
 */
export async function joinChallenge(
  userId: string,
  challengeId: string
): Promise<ChallengeParticipant> {
  const participant = await prisma.challengeParticipant.create({
    data: {
      userId,
      challengeId,
      currentProgress: 0,
    },
  });

  // Calculate initial progress
  const challenge = await prisma.challenge.findUnique({
    where: { id: challengeId },
  });

  if (challenge) {
    const progress = await calculateUserProgressForChallenge(userId, challenge);
    await updateLeaderboardEntry(challengeId, userId, progress);
  }

  return participant;
}

/**
 * Leave a challenge (delete participation record)
 */
export async function leaveChallenge(
  userId: string,
  challengeId: string
): Promise<void> {
  await prisma.challengeParticipant.delete({
    where: {
      challengeId_userId: {
        challengeId,
        userId,
      },
    },
  });

  // Also remove from leaderboard
  await prisma.challengeLeaderboard.deleteMany({
    where: {
      challengeId,
      userId,
    },
  });
}

/**
 * Update challenge progress for a user after creating a log
 * Called automatically when a new log is created
 */
export async function updateChallengeProgressForUser(
  userId: string,
  log: DailyLog
): Promise<void> {
  const now = new Date(log.date);

  // Find active challenges user is participating in
  const participations = await prisma.challengeParticipant.findMany({
    where: {
      userId,
      challenge: {
        isActive: true,
        startDate: { lte: now },
        endDate: { gte: now },
      },
    },
    include: {
      challenge: true,
    },
  });

  // Update progress for each challenge
  for (const participation of participations) {
    const progress = await calculateUserProgressForChallenge(
      userId,
      participation.challenge
    );
    await updateLeaderboardEntry(participation.challenge.id, userId, progress);
  }
}

/**
 * Get leaderboard for a challenge with pagination
 */
export async function getChallengeLeaderboard(
  challengeId: string,
  limit = 100,
  offset = 0
) {
  const entries = await prisma.challengeLeaderboard.findMany({
    where: { challengeId },
    include: {
      challenge: {
        select: {
          id: true,
          type: true,
          title: true,
        },
      },
    },
    orderBy: [{ rank: "asc" }, { score: "desc" }],
    take: limit,
    skip: offset,
  });

  // Get user info for each entry
  const enrichedEntries = await Promise.all(
    entries.map(async (entry) => {
      const user = await prisma.user.findUnique({
        where: { id: entry.userId },
        select: {
          id: true,
          name: true,
          avatar: true,
        },
      });

      return {
        ...entry,
        user,
      };
    })
  );

  const total = await prisma.challengeLeaderboard.count({
    where: { challengeId },
  });

  return {
    entries: enrichedEntries,
    total,
  };
}
