/**
 * Export Buttons Component
 * Allows users to export project logs and statistics
 */

"use client";

import { useTranslations } from "next-intl";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu";
import { Download, FileSpreadsheet, FileText } from "lucide-react";
import { toast } from "sonner";

interface DailyLog {
  date: Date | string;
  dailyStitches?: number;
  totalStitches?: number;
  timeSpent?: number | null;
  notes?: string | null;
  photoUrl?: string | null;
}

interface ProjectData {
  id: string;
  title: string;
  description?: string | null;
  totalStitches: number;
  manufacturer?: string | null;
  logs: DailyLog[];
}

interface ExportButtonsProps {
  project: ProjectData;
}

export function ExportButtons({ project }: ExportButtonsProps) {
  const t = useTranslations();

  /**
   * Export logs to CSV format
   */
  const exportToCSV = () => {
    try {
      // CSV Headers
      const headers = [
        "Date",
        "Daily Stitches",
        "Total Stitches",
        "Time Spent (min)",
        "Notes",
        "Photo URL",
      ];

      // CSV Rows
      const rows = project.logs.map((log) => [
        new Date(log.date).toISOString().split("T")[0],
        (log.dailyStitches || 0).toString(),
        (log.totalStitches || 0).toString(),
        (log.timeSpent || "").toString(),
        `"${(log.notes || "").replace(/"/g, '""')}"`, // Escape quotes
        log.photoUrl || "",
      ]);

      // Combine headers and rows
      const csvContent = [
        headers.join(","),
        ...rows.map((row) => row.join(",")),
      ].join("\n");

      // Create blob and download
      const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${project.title.replace(/[^a-z0-9]/gi, "_")}_logs.csv`;
      link.click();
      URL.revokeObjectURL(url);

      toast.success(t("projects.export.csvSuccess"));
    } catch (error) {
      console.error("Error exporting CSV:", error);
      toast.error(t("projects.export.csvError"));
    }
  };

  /**
   * Export project summary to text file
   */
  const exportSummary = () => {
    try {
      const totalLogs = project.logs.length;
      const totalStitches = project.logs.reduce(
        (sum, log) => sum + (log.dailyStitches || 0),
        0
      );
      const avgStitchesPerDay =
        totalLogs > 0 ? Math.round(totalStitches / totalLogs) : 0;
      const firstLog = project.logs[project.logs.length - 1];
      const lastLog = project.logs[0];

      const summary = `
========================================
${project.title.toUpperCase()}
========================================

Project Details:
${project.description ? `Description: ${project.description}` : ""}
${project.manufacturer ? `Manufacturer: ${project.manufacturer}` : ""}
Total Stitches (Goal): ${project.totalStitches.toLocaleString()}

Statistics:
Total Logs: ${totalLogs}
Total Stitches (Completed): ${totalStitches.toLocaleString()}
Average Stitches/Day: ${avgStitchesPerDay.toLocaleString()}
${firstLog ? `Started: ${new Date(firstLog.date).toLocaleDateString()}` : ""}
${lastLog ? `Last Updated: ${new Date(lastLog.date).toLocaleDateString()}` : ""}

Progress Logs:
${project.logs
  .map(
    (log) =>
      `${new Date(log.date).toLocaleDateString()} - ${log.dailyStitches || 0} stitches (Total: ${log.totalStitches || 0})${log.notes ? ` - ${log.notes}` : ""}`
  )
  .join("\n")}

========================================
Generated by StitchArena
${new Date().toLocaleDateString()}
========================================
      `.trim();

      const blob = new Blob([summary], { type: "text/plain;charset=utf-8;" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${project.title.replace(/[^a-z0-9]/gi, "_")}_summary.txt`;
      link.click();
      URL.revokeObjectURL(url);

      toast.success(t("projects.export.summarySuccess"));
    } catch (error) {
      console.error("Error exporting summary:", error);
      toast.error(t("projects.export.summaryError"));
    }
  };

  /**
   * Export to JSON format (complete data)
   */
  const exportToJSON = () => {
    try {
      const exportData = {
        project: {
          title: project.title,
          description: project.description,
          totalStitches: project.totalStitches,
          manufacturer: project.manufacturer,
        },
        logs: project.logs.map((log) => ({
          date: new Date(log.date).toISOString(),
          dailyStitches: log.dailyStitches || 0,
          totalStitches: log.totalStitches || 0,
          timeSpent: log.timeSpent,
          notes: log.notes,
          hasPhoto: !!log.photoUrl,
        })),
        exportDate: new Date().toISOString(),
      };

      const jsonContent = JSON.stringify(exportData, null, 2);
      const blob = new Blob([jsonContent], {
        type: "application/json;charset=utf-8;",
      });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${project.title.replace(/[^a-z0-9]/gi, "_")}_data.json`;
      link.click();
      URL.revokeObjectURL(url);

      toast.success(t("projects.export.jsonSuccess"));
    } catch (error) {
      console.error("Error exporting JSON:", error);
      toast.error(t("projects.export.jsonError"));
    }
  };

  if (project.logs.length === 0) {
    return null;
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2">
          <Download className="h-4 w-4" />
          {t("projects.export.button")}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-48">
        <DropdownMenuItem onClick={exportToCSV} className="gap-2">
          <FileSpreadsheet className="h-4 w-4" />
          {t("projects.export.csv")}
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportSummary} className="gap-2">
          <FileText className="h-4 w-4" />
          {t("projects.export.summary")}
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={exportToJSON} className="gap-2 text-xs">
          <FileText className="h-4 w-4" />
          {t("projects.export.json")}
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
