"use client";

import { useEffect, useState } from "react";
import { AdminTable } from "@/components/admin/admin-table";
import { ExportButton } from "@/components/admin/export-button";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Trash2, Edit, Users } from "lucide-react";

interface Challenge {
  id: string;
  type: string;
  title: string;
  description: string | null;
  startDate: Date;
  endDate: Date;
  targetValue: number;
  isActive: boolean;
  isAutoGenerated: boolean;
  createdAt: Date;
  creator: {
    id: string;
    name: string | null;
    email: string;
  } | null;
  _count: {
    participants: number;
    leaderboard: number;
  };
}

export default function AdminChallengesPage() {
  const [challenges, setChallenges] = useState<Challenge[]>([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [typeFilter, setTypeFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");
  const [deleteDialog, setDeleteDialog] = useState<{
    open: boolean;
    challenge: Challenge | null;
  }>({ open: false, challenge: null });
  const [editDialog, setEditDialog] = useState<{
    open: boolean;
    challenge: Challenge | null;
  }>({ open: false, challenge: null });
  const [editForm, setEditForm] = useState<any>({});

  const fetchChallenges = async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({
        page: page.toString(),
        limit: "20",
        type: typeFilter,
        status: statusFilter,
      });

      const res = await fetch(`/api/admin/challenges?${params}`);
      const data = await res.json();

      setChallenges(data.challenges);
      setTotalPages(data.pagination.totalPages);
    } catch (error) {
      console.error("Failed to fetch challenges:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchChallenges();
  }, [page, typeFilter, statusFilter]);

  const handleDelete = async (challengeId: string) => {
    const res = await fetch(`/api/admin/challenges/${challengeId}`, {
      method: "DELETE",
    });

    if (res.ok) {
      fetchChallenges();
    } else {
      throw new Error("Failed to delete challenge");
    }
  };

  const handleEdit = async () => {
    if (!editDialog.challenge) return;

    const res = await fetch(`/api/admin/challenges/${editDialog.challenge.id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(editForm),
    });

    if (res.ok) {
      setEditDialog({ open: false, challenge: null });
      setEditForm({});
      fetchChallenges();
    } else {
      throw new Error("Failed to update challenge");
    }
  };

  const openEditDialog = (challenge: Challenge) => {
    setEditDialog({ open: true, challenge });
    setEditForm({
      title: challenge.title,
      description: challenge.description || "",
      startDate: new Date(challenge.startDate).toISOString().split("T")[0],
      endDate: new Date(challenge.endDate).toISOString().split("T")[0],
      targetValue: challenge.targetValue,
      isActive: challenge.isActive,
    });
  };

  const getTypeBadge = (type: string) => {
    const variants: Record<string, any> = {
      speed: "default",
      streak: "outline",
      completion: "secondary",
    };

    const labels: Record<string, string> = {
      speed: "Speed",
      streak: "Streak",
      completion: "Completion",
    };

    return (
      <Badge variant={variants[type] || "outline"} className="rounded-full">
        {labels[type] || type}
      </Badge>
    );
  };

  const formatDate = (date: Date) => {
    return new Date(date).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  };

  const columns = [
    {
      key: "title",
      label: "Challenge",
      render: (challenge: Challenge) => (
        <div>
          <p className="font-medium">{challenge.title}</p>
          {challenge.description && (
            <p className="text-xs text-muted-foreground line-clamp-1">
              {challenge.description}
            </p>
          )}
        </div>
      ),
    },
    {
      key: "type",
      label: "Type",
      render: (challenge: Challenge) => getTypeBadge(challenge.type),
    },
    {
      key: "status",
      label: "Status",
      render: (challenge: Challenge) => (
        <div className="flex gap-1">
          <Badge
            variant={challenge.isActive ? "default" : "secondary"}
            className="rounded-full"
          >
            {challenge.isActive ? "Active" : "Inactive"}
          </Badge>
          {challenge.isAutoGenerated && (
            <Badge variant="outline" className="rounded-full text-xs">
              Auto
            </Badge>
          )}
        </div>
      ),
    },
    {
      key: "dates",
      label: "Period",
      render: (challenge: Challenge) => (
        <span className="text-xs">
          {formatDate(challenge.startDate)} - {formatDate(challenge.endDate)}
        </span>
      ),
    },
    {
      key: "target",
      label: "Target",
      render: (challenge: Challenge) => (
        <span className="text-sm">{challenge.targetValue.toLocaleString()}</span>
      ),
    },
    {
      key: "participants",
      label: "Participants",
      render: (challenge: Challenge) => (
        <div className="flex items-center gap-1 text-sm">
          <Users className="h-4 w-4" />
          {challenge._count.participants}
        </div>
      ),
    },
    {
      key: "actions",
      label: "Actions",
      render: (challenge: Challenge) => (
        <div className="flex gap-1">
          <Button
            variant="ghost"
            size="sm"
            className="rounded-full"
            onClick={() => openEditDialog(challenge)}
          >
            <Edit className="h-4 w-4" />
          </Button>
          <Button
            variant="ghost"
            size="sm"
            className="rounded-full text-destructive hover:text-destructive"
            onClick={() => setDeleteDialog({ open: true, challenge })}
          >
            <Trash2 className="h-4 w-4" />
          </Button>
        </div>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold">Challenges</h1>
          <p className="text-muted-foreground">Manage community challenges</p>
        </div>
      </div>

      {/* Filters */}
      <div className="flex gap-4">
        <Select
          value={typeFilter}
          onValueChange={(value) => {
            setTypeFilter(value);
            setPage(1);
          }}
        >
          <SelectTrigger className="w-[180px] rounded-full">
            <SelectValue placeholder="Type" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Types</SelectItem>
            <SelectItem value="speed">Speed</SelectItem>
            <SelectItem value="streak">Streak</SelectItem>
            <SelectItem value="completion">Completion</SelectItem>
          </SelectContent>
        </Select>

        <Select
          value={statusFilter}
          onValueChange={(value) => {
            setStatusFilter(value);
            setPage(1);
          }}
        >
          <SelectTrigger className="w-[180px] rounded-full">
            <SelectValue placeholder="Status" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Status</SelectItem>
            <SelectItem value="active">Active</SelectItem>
            <SelectItem value="inactive">Inactive</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* Table */}
      <AdminTable
        columns={columns}
        data={challenges}
        loading={loading}
        pagination={{
          page,
          totalPages,
          onPageChange: setPage,
        }}
        emptyMessage="No challenges found"
      />

      {/* Edit Dialog */}
      <Dialog
        open={editDialog.open}
        onOpenChange={(open) => {
          if (!open) {
            setEditDialog({ open: false, challenge: null });
            setEditForm({});
          }
        }}
      >
        <DialogContent className="rounded-2xl">
          <DialogHeader>
            <DialogTitle>Edit Challenge</DialogTitle>
            <DialogDescription>
              Update challenge details
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4">
            <div className="space-y-2">
              <Label>Title</Label>
              <Input
                value={editForm.title || ""}
                onChange={(e) => setEditForm({ ...editForm, title: e.target.value })}
                className="rounded-full"
              />
            </div>

            <div className="space-y-2">
              <Label>Description</Label>
              <Textarea
                value={editForm.description || ""}
                onChange={(e) =>
                  setEditForm({ ...editForm, description: e.target.value })
                }
                className="rounded-xl"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Start Date</Label>
                <Input
                  type="date"
                  value={editForm.startDate || ""}
                  onChange={(e) =>
                    setEditForm({ ...editForm, startDate: e.target.value })
                  }
                  className="rounded-full"
                />
              </div>

              <div className="space-y-2">
                <Label>End Date</Label>
                <Input
                  type="date"
                  value={editForm.endDate || ""}
                  onChange={(e) =>
                    setEditForm({ ...editForm, endDate: e.target.value })
                  }
                  className="rounded-full"
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label>Target Value</Label>
              <Input
                type="number"
                value={editForm.targetValue || ""}
                onChange={(e) =>
                  setEditForm({ ...editForm, targetValue: e.target.value })
                }
                className="rounded-full"
              />
            </div>

            <div className="flex items-center justify-between">
              <Label>Active</Label>
              <Switch
                checked={editForm.isActive || false}
                onCheckedChange={(checked) =>
                  setEditForm({ ...editForm, isActive: checked })
                }
              />
            </div>
          </div>

          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setEditDialog({ open: false, challenge: null });
                setEditForm({});
              }}
              className="rounded-full"
            >
              Cancel
            </Button>
            <Button onClick={handleEdit} className="rounded-full">
              Save Changes
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Dialog */}
      <AlertDialog
        open={deleteDialog.open}
        onOpenChange={(open) => setDeleteDialog({ open, challenge: null })}
      >
        <AlertDialogContent className="rounded-2xl">
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Challenge?</AlertDialogTitle>
            <AlertDialogDescription>
              This will permanently delete "{deleteDialog.challenge?.title}" and all
              participant data. This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel className="rounded-full">Cancel</AlertDialogCancel>
            <AlertDialogAction
              className="rounded-full bg-destructive hover:bg-destructive/90"
              onClick={async () => {
                if (deleteDialog.challenge) {
                  await handleDelete(deleteDialog.challenge.id);
                  setDeleteDialog({ open: false, challenge: null });
                }
              }}
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
