"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useTranslations } from "next-intl";
import { useSession } from "next-auth/react";
import { Button } from "@/components/ui/button";
import { ChallengeCard } from "@/components/challenges/challenge-card";
import { CreateChallengeDialog } from "@/components/challenges/create-challenge-dialog";
import { EligibilityBanner } from "@/components/challenges/eligibility-banner";
import { Skeleton } from "@/components/ui/skeleton";
import { Trophy } from "lucide-react";

type StatusFilter = "active" | "upcoming" | "past" | "all";
type TypeFilter = "all" | "speed" | "streak" | "completion";

interface Challenge {
  id: string;
  type: string;
  title: string;
  description?: string | null;
  startDate: string;
  endDate: string;
  targetValue: number;
  isAutoGenerated?: boolean;
  createdBy?: string | null;
  creator?: {
    name?: string | null;
  } | null;
  _count?: {
    participants: number;
  };
}

interface UserParticipation {
  challengeId: string;
  currentProgress: number;
}

interface EligibilityData {
  eligible: boolean;
  tenure: number;
  currentStreak: number;
  tenureRequired: number;
  streakRequired: number;
  activeCount: number;
  maxActive: number;
  canCreate: boolean;
}

export default function ChallengesPage() {
  const t = useTranslations();
  const { data: session } = useSession();
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("active");
  const [typeFilter, setTypeFilter] = useState<TypeFilter>("all");

  // Fetch challenges
  const { data: challenges, isLoading: challengesLoading, refetch: refetchChallenges } = useQuery<Challenge[]>({
    queryKey: ["challenges", statusFilter === "all" ? undefined : statusFilter, typeFilter === "all" ? undefined : typeFilter],
    queryFn: async () => {
      const params = new URLSearchParams();
      if (statusFilter !== "all") params.append("status", statusFilter);
      if (typeFilter !== "all") params.append("type", typeFilter);

      const response = await fetch(`/api/challenges?${params}`);
      const json = await response.json();
      return json.data || [];
    },
  });

  // Fetch eligibility if logged in
  const { data: eligibility } = useQuery<EligibilityData>({
    queryKey: ["challenge-eligibility"],
    queryFn: async () => {
      const response = await fetch("/api/challenges/eligibility");
      if (!response.ok) return null;
      const json = await response.json();
      return json.data;
    },
    enabled: !!session?.user,
  });

  // Fetch user participations if logged in
  const { data: participations } = useQuery<UserParticipation[]>({
    queryKey: ["user-challenge-participations"],
    queryFn: async () => {
      if (!session?.user) return [];
      const response = await fetch("/api/challenges/participations");
      if (!response.ok) return [];
      const json = await response.json();
      return json.data || [];
    },
    enabled: !!session?.user,
  });

  // Create participation map for quick lookup
  const participationMap = new Map(
    participations?.map((p) => [p.challengeId, p]) || []
  );

  return (
    <div>
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center justify-between gap-4 mb-4">
          <div className="flex items-center gap-4">
            <div className="p-3 rounded-2xl bg-warning/10 shadow-sm">
              <Trophy className="h-10 w-10 text-warning" />
            </div>
            <div>
              <h1 className="text-4xl font-bold text-foreground">
                {t("challenges.title")}
              </h1>
              <p className="text-muted-foreground mt-1">{t("challenges.subtitle")}</p>
            </div>
          </div>
          {session?.user && eligibility?.canCreate && (
            <CreateChallengeDialog onSuccess={refetchChallenges} />
          )}
        </div>

        {/* Quick Stats */}
        {challenges && challenges.length > 0 && (
          <div className="grid grid-cols-3 gap-3">
            <div className="rounded-2xl bg-success/5 border-success/10 border p-4 shadow-sm">
              <div className="flex items-center gap-2 mb-1">
                <div className="h-2 w-2 rounded-full bg-success animate-pulse" />
                <span className="text-xs font-medium text-success">Active</span>
              </div>
              <p className="text-2xl font-bold text-success">
                {challenges.filter(c => {
                  const now = new Date();
                  const start = new Date(c.startDate);
                  const end = new Date(c.endDate);
                  return now >= start && now <= end;
                }).length}
              </p>
            </div>

            <div className="rounded-2xl bg-info/5 border-info/10 border p-4 shadow-sm">
              <div className="flex items-center gap-2 mb-1">
                <Trophy className="h-3 w-3 text-info" />
                <span className="text-xs font-medium text-info">Total</span>
              </div>
              <p className="text-2xl font-bold text-info">{challenges.length}</p>
            </div>

            <div className="rounded-2xl bg-warning/5 border-warning/10 border p-4 shadow-sm">
              <div className="flex items-center gap-2 mb-1">
                <Trophy className="h-3 w-3 text-warning" />
                <span className="text-xs font-medium text-warning">Joined</span>
              </div>
              <p className="text-2xl font-bold text-warning">
                {participations?.length || 0}
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Eligibility Banner */}
      {session?.user && eligibility && !eligibility.canCreate && (
        <div className="mb-6">
          <EligibilityBanner
            tenure={eligibility.tenure}
            currentStreak={eligibility.currentStreak}
            tenureRequired={eligibility.tenureRequired}
            streakRequired={eligibility.streakRequired}
          />
        </div>
      )}

      {/* Filters */}
      <div className="mb-6 grid gap-4 sm:grid-cols-2">
        {/* Status Filter */}
        <div className="rounded-2xl bg-primary/5 border-primary/10 border p-5 shadow-sm">
          <h3 className="mb-3 text-sm font-semibold text-primary flex items-center gap-2">
            <Trophy className="h-4 w-4" />
            {t("common.status")}
          </h3>
          <div className="flex flex-wrap gap-2">
            {(["all", "active", "upcoming", "past"] as StatusFilter[]).map((status) => (
              <Button
                key={status}
                variant={statusFilter === status ? "default" : "outline"}
                size="sm"
                onClick={() => setStatusFilter(status)}
                className="rounded-full"
              >
                {status === "all"
                  ? t("common.all")
                  : t(`challenges.filters.${status}`)}
              </Button>
            ))}
          </div>
        </div>

        {/* Type Filter */}
        <div className="rounded-2xl bg-success/5 border-success/10 border p-5 shadow-sm">
          <h3 className="mb-3 text-sm font-semibold text-success flex items-center gap-2">
            <Trophy className="h-4 w-4" />
            {t("common.type")}
          </h3>
          <div className="flex flex-wrap gap-2">
            <Button
              variant={typeFilter === "all" ? "default" : "outline"}
              size="sm"
              onClick={() => setTypeFilter("all")}
              className="rounded-full"
            >
              {t("common.all")}
            </Button>
            {(["speed", "streak", "completion"] as TypeFilter[]).map((type) => (
              <Button
                key={type}
                variant={typeFilter === type ? "default" : "outline"}
                size="sm"
                onClick={() => setTypeFilter(type)}
                className="rounded-full"
              >
                {type === "speed" && "⚡ "}
                {type === "streak" && "🔥 "}
                {type === "completion" && "✨ "}
                {t(`challenges.types.${type}`)}
              </Button>
            ))}
          </div>
        </div>
      </div>

      {/* Challenges Grid */}
      {challengesLoading ? (
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {[1, 2, 3, 4, 5, 6].map((i) => (
            <Skeleton key={i} className="h-[300px]" />
          ))}
        </div>
      ) : challenges && challenges.length > 0 ? (
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {challenges.map((challenge) => (
            <ChallengeCard
              key={challenge.id}
              challenge={challenge}
              userParticipation={participationMap.get(challenge.id)}
              currentUserId={session?.user?.id}
            />
          ))}
        </div>
      ) : (
        <div className="rounded-2xl bg-muted/30 border border-border p-16 text-center">
          <div className="inline-flex p-6 rounded-full bg-warning/10 mb-6 shadow-sm">
            <Trophy className="h-16 w-16 text-warning" />
          </div>
          <h3 className="text-2xl font-bold mb-3">
            {t("challenges.noChallenges")}
          </h3>
          <p className="text-muted-foreground max-w-md mx-auto mb-6">
            {t("challenges.noChallengesDescription")}
          </p>
          {session?.user && eligibility?.canCreate && (
            <CreateChallengeDialog onSuccess={refetchChallenges} />
          )}
        </div>
      )}
    </div>
  );
}
