/**
 * Cron job to automatically generate weekly challenges
 * Runs every Monday at 00:00 UTC
 */

import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { addDays, startOfWeek, endOfWeek } from "date-fns";

/**
 * Verify that the request is from Vercel Cron
 */
function verifyCronRequest(request: Request): boolean {
  const authHeader = request.headers.get("authorization");

  // In development, allow requests without auth
  if (process.env.NODE_ENV === "development") {
    return true;
  }

  // In production, verify the cron secret
  const cronSecret = process.env.CRON_SECRET;
  if (!cronSecret) {
    console.error("CRON_SECRET not configured");
    return false;
  }

  return authHeader === `Bearer ${cronSecret}`;
}

/**
 * Generate a weekly challenge
 */
async function generateWeeklyChallenge(
  type: "speed" | "streak" | "completion",
  startDate: Date,
  endDate: Date
): Promise<void> {
  const challengeConfig = {
    speed: {
      title: "Weekly Speed Challenge",
      description: "Stitch as many stitches as you can this week! The fastest stitcher wins.",
      targetValue: 1000, // Suggested target, actual ranking is by total stitches
    },
    streak: {
      title: "Weekly Streak Challenge",
      description: "Build the longest daily streak this week. Log progress every day to win!",
      targetValue: 7, // 7-day streak
    },
    completion: {
      title: "Weekly Completion Challenge",
      description: "Complete as many projects as possible this week. Quality and speed combined!",
      targetValue: 1, // At least 1 project
    },
  };

  const config = challengeConfig[type];

  await prisma.challenge.create({
    data: {
      title: config.title,
      description: config.description,
      type,
      targetValue: config.targetValue,
      startDate,
      endDate,
      isActive: true,
      isAutoGenerated: true,
      createdBy: "system", // System-generated challenge
    },
  });
}

/**
 * GET /api/cron/challenges/generate
 * Generate weekly challenges for the upcoming week
 */
export async function GET(request: Request) {
  // Verify cron request
  if (!verifyCronRequest(request)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    // Calculate next week's date range (Monday to Sunday)
    const today = new Date();
    const nextMonday = addDays(startOfWeek(today, { weekStartsOn: 1 }), 7);
    const nextSunday = endOfWeek(nextMonday, { weekStartsOn: 1 });

    // Check if challenges for next week already exist
    const existingChallenges = await prisma.challenge.count({
      where: {
        isAutoGenerated: true,
        startDate: {
          gte: nextMonday,
          lt: addDays(nextMonday, 1), // Same day as nextMonday
        },
      },
    });

    if (existingChallenges > 0) {
      return NextResponse.json({
        message: "Challenges for next week already exist",
        skipped: true,
      });
    }

    // Generate 2-3 challenges for next week
    const challengeTypes: Array<"speed" | "streak" | "completion"> = [
      "speed",
      "streak",
    ];

    // Randomly add completion challenge (50% chance)
    if (Math.random() > 0.5) {
      challengeTypes.push("completion");
    }

    for (const type of challengeTypes) {
      await generateWeeklyChallenge(type, nextMonday, nextSunday);
    }

    return NextResponse.json({
      message: `Generated ${challengeTypes.length} challenges for next week`,
      startDate: nextMonday.toISOString(),
      endDate: nextSunday.toISOString(),
      types: challengeTypes,
    });
  } catch (error) {
    console.error("Error generating challenges:", error);
    return NextResponse.json(
      { error: "Failed to generate challenges" },
      { status: 500 }
    );
  }
}
