"use client";

import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import { useTranslations } from "next-intl";
import { differenceInDays, isPast, isFuture } from "date-fns";
import Link from "next/link";
import { Trophy, Users, Calendar, Target, Sparkles, User, Zap, Flame, CheckCircle } from "lucide-react";

interface ChallengeCardProps {
  challenge: {
    id: string;
    type: string;
    title: string;
    description?: string | null;
    startDate: Date | string;
    endDate: Date | string;
    targetValue: number;
    isAutoGenerated?: boolean;
    createdBy?: string | null;
    creator?: {
      name?: string | null;
    } | null;
    _count?: {
      participants: number;
    };
  };
  userParticipation?: {
    currentProgress: number;
  } | null;
  currentUserId?: string;
}

export function ChallengeCard({
  challenge,
  userParticipation,
  currentUserId,
}: ChallengeCardProps) {
  const t = useTranslations();
  const now = new Date();
  const startDate = new Date(challenge.startDate);
  const endDate = new Date(challenge.endDate);

  const isActive = now >= startDate && now <= endDate;
  const isUpcoming = isFuture(startDate);
  const isPastChallenge = isPast(endDate);

  const daysRemaining = isActive ? differenceInDays(endDate, now) : 0;
  const participantCount = challenge._count?.participants || 0;
  const isCreatedByCurrentUser = currentUserId && challenge.createdBy === currentUserId;

  // Calculate progress percentage
  const progressPercent = userParticipation
    ? Math.min((userParticipation.currentProgress / challenge.targetValue) * 100, 100)
    : 0;

  // Get status badge
  const getStatusBadge = () => {
    if (isPastChallenge) {
      return <Badge variant="secondary" className="rounded-full">{t("challenges.filters.past")}</Badge>;
    }
    if (isUpcoming) {
      return <Badge variant="outline" className="rounded-full">{t("challenges.filters.upcoming")}</Badge>;
    }
    return <Badge variant="default" className="rounded-full">{t("challenges.filters.active")}</Badge>;
  };

  // Get type badge and icon
  const getTypeBadge = () => {
    const typeConfig: Record<string, { color: string; icon: React.ReactElement; emoji: string }> = {
      speed: {
        color: "bg-info/10 text-info border-info/20",
        icon: <Zap className="h-3 w-3" />,
        emoji: "⚡"
      },
      streak: {
        color: "bg-success/10 text-success border-success/20",
        icon: <Flame className="h-3 w-3" />,
        emoji: "🔥"
      },
      completion: {
        color: "bg-warning/10 text-warning border-warning/20",
        icon: <CheckCircle className="h-3 w-3" />,
        emoji: "✨"
      },
    };

    const config = typeConfig[challenge.type] || typeConfig.speed;

    return (
      <Badge className={`rounded-full gap-1 ${config.color}`}>
        <span>{config.emoji}</span>
        {t(`challenges.types.${challenge.type}`)}
      </Badge>
    );
  };

  // Get background color based on type
  const getCardBg = () => {
    if (challenge.type === "speed") return "bg-info/5 border-info/10";
    if (challenge.type === "streak") return "bg-success/5 border-success/10";
    if (challenge.type === "completion") return "bg-warning/5 border-warning/10";
    return "bg-muted/30 border-border";
  };

  return (
    <Card className={`hover:shadow-lg transition-all duration-300 hover:scale-[1.02] rounded-2xl border shadow-sm ${getCardBg()}`}>
      <CardHeader>
        <div className="flex items-start justify-between gap-2 mb-3">
          <div className="flex gap-2 flex-wrap">
            {getStatusBadge()}
            {getTypeBadge()}
          </div>
          <div className="p-2 rounded-xl bg-background/80 backdrop-blur-sm shadow-sm">
            <Trophy className="h-5 w-5 text-primary" />
          </div>
        </div>

        <CardTitle className="text-xl mb-2">{challenge.title}</CardTitle>

        <div className="flex gap-2 flex-wrap mb-2">
          {!challenge.createdBy ? (
            <Badge variant="secondary" className="gap-1 rounded-full text-[10px]">
              <Sparkles className="h-3 w-3" />
              {t("challenges.autoGenerated")}
            </Badge>
          ) : (
            <Badge variant="outline" className="gap-1 rounded-full text-[10px]">
              <User className="h-3 w-3" />
              {isCreatedByCurrentUser
                ? t("challenges.createdByYou")
                : t("challenges.createdBy", {
                    name: challenge.creator?.name || t("challenges.user"),
                  })}
            </Badge>
          )}
        </div>

        {challenge.description && (
          <p className="text-sm text-muted-foreground line-clamp-2">
            {challenge.description}
          </p>
        )}
      </CardHeader>

      <CardContent className="space-y-4">
        {/* Stats */}
        <div className="grid grid-cols-2 gap-3">
          <div className="flex items-center gap-2 p-3 rounded-xl bg-background/60 backdrop-blur-sm">
            <Users className="h-4 w-4 text-primary" />
            <div className="flex flex-col">
              <span className="text-xs text-muted-foreground">{t("challenges.participants")}</span>
              <span className="font-semibold">{participantCount}</span>
            </div>
          </div>

          {isActive && (
            <div className="flex items-center gap-2 p-3 rounded-xl bg-background/60 backdrop-blur-sm">
              <Calendar className="h-4 w-4 text-success" />
              <div className="flex flex-col">
                <span className="text-xs text-muted-foreground">Days left</span>
                <span className="font-semibold">{daysRemaining}</span>
              </div>
            </div>
          )}

          <div className="flex items-center gap-2 col-span-2 p-3 rounded-xl bg-background/60 backdrop-blur-sm">
            <Target className="h-4 w-4 text-warning" />
            <div className="flex flex-col">
              <span className="text-xs text-muted-foreground">
                {challenge.type === "speed" ? t("challenges.targetMotivation") : t("challenges.target")}
              </span>
              <span className="font-semibold">{challenge.targetValue.toLocaleString()}</span>
            </div>
          </div>
        </div>

        {/* User Progress */}
        {userParticipation && (
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span className="text-muted-foreground">{t("challenges.yourProgress")}</span>
              <span className="font-medium">
                {userParticipation.currentProgress.toLocaleString()} / {challenge.targetValue.toLocaleString()}
              </span>
            </div>
            <Progress value={progressPercent} className="rounded-full" />
          </div>
        )}

        {/* View Details Button */}
        <Link href={`/challenges/${challenge.id}`}>
          <Button className="w-full rounded-full" variant={userParticipation ? "default" : "outline"}>
            <Trophy className="mr-2 h-4 w-4" />
            {t("common.viewDetails")}
          </Button>
        </Link>
      </CardContent>
    </Card>
  );
}
