import { NextRequest, NextResponse } from "next/server";
import { requireAdmin } from "@/lib/admin";
import { prisma } from "@/lib/prisma";

export async function GET(request: NextRequest) {
  const { session, error } = await requireAdmin();
  if (error) return error;

  try {
    const { searchParams } = new URL(request.url);
    const page = parseInt(searchParams.get("page") || "1");
    const limit = parseInt(searchParams.get("limit") || "20");
    const type = searchParams.get("type") || "all"; // all | speed | streak | completion
    const status = searchParams.get("status") || "all"; // all | active | inactive

    const skip = (page - 1) * limit;

    // Build where clause
    const where: any = {};

    if (type !== "all") {
      where.type = type;
    }

    if (status === "active") {
      where.isActive = true;
    } else if (status === "inactive") {
      where.isActive = false;
    }

    // Fetch challenges with creator and participant count
    const [challenges, total] = await Promise.all([
      prisma.challenge.findMany({
        where,
        select: {
          id: true,
          type: true,
          title: true,
          description: true,
          startDate: true,
          endDate: true,
          targetValue: true,
          isActive: true,
          isAutoGenerated: true,
          createdAt: true,
          creator: {
            select: {
              id: true,
              name: true,
              email: true,
            },
          },
          _count: {
            select: {
              participants: true,
              leaderboard: true,
            },
          },
        },
        orderBy: { createdAt: "desc" },
        skip,
        take: limit,
      }),
      prisma.challenge.count({ where }),
    ]);

    return NextResponse.json({
      challenges,
      pagination: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    });
  } catch (err) {
    console.error("Failed to fetch challenges:", err);
    return NextResponse.json(
      { error: "Failed to fetch challenges" },
      { status: 500 }
    );
  }
}
